import React, { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'

const TONES=['Professionell','Freundlich','Direkt','Inspirierend','Humorvoll','Empathisch','Analytisch','Motivierend','Authentisch','Kreativ','Sachlich','Leidenschaftlich','Mutig']
const FORM=[{v:'du',l:'Du-Form',d:'Persoenlich'},{v:'sie',l:'Sie-Form',d:'Formell'},{v:'mixed',l:'Gemischt',d:'Kontextabhaengig'}]
const JARG=[{v:'technical',l:'Fachspezifisch'},{v:'casual',l:'Umgangssprachlich'},{v:'mixed',l:'Gemischt'}]
const VOICE=[{v:'active',l:'Aktiv'},{v:'passive',l:'Passiv'}]
const E0={name:'',is_active:true,brand_name:'',brand_background:'',mission:'',vision:'',values:'',personality:'',tone_attributes:[],word_choice:'',sentence_style:'',jargon_level:'mixed',voice_style:'active',formality:'du',dos:'',donts:'',target_audience:'',example_texts:'',ai_summary:''}
const In=({v,fn,ph})=><input value={v||''} onChange={e=>fn(e.target.value)} placeholder={ph} style={{width:'100%',padding:'8px 11px',border:'1.5px solid #dde3ea',borderRadius:8,fontSize:13,boxSizing:'border-box'}}/>
const Tx=({v,fn,r=3,ph})=><textarea value={v||''} onChange={e=>fn(e.target.value)} rows={r} placeholder={ph} style={{width:'100%',padding:'8px 11px',border:'1.5px solid #dde3ea',borderRadius:8,fontSize:13,resize:'vertical',boxSizing:'border-box'}}/>
const Lb=({l,h})=><div style={{marginBottom:10}}><div style={{fontSize:11,fontWeight:700,color:'#555',textTransform:'uppercase',letterSpacing:'.5px',marginBottom:3}}>{l}</div>{h&&<div style={{fontSize:11,color:'#aaa',marginBottom:4}}>{h}</div>}</div>
const Sc=({t,ch})=><div style={{background:'#fff',borderRadius:12,border:'1px solid #e8ecf0',marginBottom:14}}><div style={{padding:'11px 16px',borderBottom:'1px solid #f0f0f0',fontWeight:700,fontSize:13}}>{t}</div><div style={{padding:'15px 16px',display:'flex',flexDirection:'column',gap:11}}>{ch}</div></div>

export default function BrandVoice({session}){
const[voices,setVoices]=useState([])
const[ed,setEd]=useState(null)
const[form,setForm]=useState(E0)
const[saving,setSaving]=useState(false)
const[saved,setSaved]=useState(false)
const[ai,setAi]=useState(false)
const[tab,setTab]=useState('id')
useEffect(()=>{load()},[])
async function load(){const{data}=await supabase.from('brand_voices').select('*').eq('user_id',session.user.id).order('updated_at',{ascending:false});setVoices(data||[])}
const s=k=>v=>setForm(f=>({...f,[k]:v}))
const tog=t=>setForm(f=>{const a=f.tone_attributes||[];return{...f,tone_attributes:a.includes(t)?a.filter(x=>x!==t):[...a,t]}})
async function genSummary(){setAi(true);const{data:{session:ss}}=await supabase.auth.getSession();const p=['Erstelle eine praezise Brand Voice Anweisung (max 200 Woerter) fuer LinkedIn-Kommentare.'];if(form.brand_name)p.push('Marke: '+form.brand_name);if(form.personality)p.push('Persoenlichkeit: '+form.personality);if(form.tone_attributes?.length)p.push('Ton: '+form.tone_attributes.join(', '));if(form.formality==='du')p.push('Ansprache: Du-Form');if(form.formality==='sie')p.push('Ansprache: Sie-Form');if(form.dos)p.push('Dos: '+form.dos);if(form.donts)p.push('Donts: '+form.donts);if(form.target_audience)p.push('Zielgruppe: '+form.target_audience);if(form.example_texts)p.push('Beispiele:\n'+form.example_texts.slice(0,500));try{const r=await fetch('https://jdhajqpgfrsuoluaesjn.supabase.co/functions/v1/generate',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+ss.access_token},body:JSON.stringify({type:'brand_voice_summary',prompt:p.join('\n')})});const d=await r.json();if(d.summary||d.comment){setForm(f=>({...f,ai_summary:d.summary||d.comment}));setTab('sum')}}catch(e){console.error(e)};setAi(false)}
async function save(){if(!form.name?.trim())return;setSaving(true);const p={...form,user_id:session.user.id};if(ed==='new')await supabase.from('brand_voices').insert(p);else await supabase.from('brand_voices').update(p).eq('id',ed.id);await load();setSaving(false);setSaved(true);setTimeout(()=>{setSaved(false);setEd(null)},1500)}
async function activate(id){await supabase.from('brand_voices').update({is_active:false}).eq('user_id',session.user.id);await supabase.from('brand_voices').update({is_active:true}).eq('id',id);await load()}
const TABS=[{id:'id',l:'Marke'},{id:'lang',l:'Sprache'},{id:'aud',l:'Zielgruppe'},{id:'sum',l:'Summary'}]

if(ed!==null)return(<div style={{maxWidth:800}}>
  <div style={{display:'flex',alignItems:'center',gap:12,marginBottom:20}}><button onClick={()=>setEd(null)} style={{background:'none',border:'none',fontSize:20,cursor:'pointer',color:'#888'}}>&#8592;</button><div><h1 style={{fontSize:19,fontWeight:800,margin:0}}>{ed==='new'?'Neue Brand Voice':'Brand Voice bearbeiten'}</h1><p style={{fontSize:12,color:'#888',margin:0}}>Kommunikationsstil fuer LinkedIn-Kommentare</p></div></div>
  <div style={{display:'flex',gap:10,marginBottom:14,alignItems:'center'}}><In v={form.name} fn={s('name')} ph="Name (z.B. LinkedIn Persoenlich)"/><label style={{display:'flex',alignItems:'center',gap:6,fontSize:12,color:'#555',cursor:'pointer',whiteSpace:'nowrap'}}><input type="checkbox" checked={form.is_active} onChange={e=>s('is_active')(e.target.checked)}/>Aktiv</label></div>
  <div style={{display:'flex',gap:4,borderBottom:'2px solid #eee',marginBottom:14}}>{TABS.map(t=><button key={t.id} onClick={()=>setTab(t.id)} style={{padding:'7px 14px',border:'none',background:'none',cursor:'pointer',fontSize:13,fontWeight:600,color:tab===t.id?'#0a66c2':'#888',borderBottom:tab===t.id?'2px solid #0a66c2':'2px solid transparent',marginBottom:-2}}>{t.l}</button>)}</div>
  {tab==='id'&&<><Sc t="Markenidentitaet" ch={<><div><Lb l="Markenname"/><In v={form.brand_name} fn={s('brand_name')} ph="z.B. LinkedIn Consulting GmbH"/></div><div><Lb l="Hintergrund" h="Was tut die Marke?"/><Tx v={form.brand_background} fn={s('brand_background')} r={2} ph="Wir sind ein B2B-Unternehmen..."/></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><div><Lb l="Mission"/><Tx v={form.mission} fn={s('mission')} r={2} ph="Wir helfen..."/></div><div><Lb l="Vision"/><Tx v={form.vision} fn={s('vision')} r={2} ph="Eine Welt in der..."/></div></div><div><Lb l="Werte"/><In v={form.values} fn={s('values')} ph="Ehrlichkeit, Innovation..."/></div></>}/><Sc t="Persoenlichkeit" ch={<><div><Lb l="Beschreibung"/><Tx v={form.personality} fn={s('personality')} r={2} ph="Wir kommunizieren direkt..."/></div><div><Lb l="Ton-Attribute (3-6)"/><div style={{display:'flex',flexWrap:'wrap',gap:7,marginTop:4}}>{TONES.map(t=>{const on=(form.tone_attributes||[]).includes(t);return <button key={t} onClick={()=>tog(t)} style={{padding:'4px 12px',borderRadius:14,fontSize:12,fontWeight:600,cursor:'pointer',border:'none',background:on?'#0a66c2':'#f0f0f0',color:on?'#fff':'#555'}}>{t}</button>})}</div></div></>}/></>}
  {tab==='lang'&&<><Sc t="Ansprache" ch={<><div><Lb l="Foermlichkeit"/><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:10}}>{FORM.map(o=><button key={o.v} onClick={()=>s('formality')(o.v)} style={{padding:'9px 12px',borderRadius:9,cursor:'pointer',textAlign:'left',border:form.formality===o.v?'2px solid #0a66c2':'1.5px solid #dde3ea',background:form.formality===o.v?'#e8f0fb':'#fff'}}><div style={{fontWeight:700,fontSize:13,color:form.formality===o.v?'#0a66c2':'#333'}}>{o.l}</div><div style={{fontSize:11,color:'#888'}}>{o.d}</div></button>)}</div></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><div><Lb l="Sprachebene"/>{JARG.map(o=><button key={o.v} onClick={()=>s('jargon_level')(o.v)} style={{display:'flex',width:'100%',padding:'7px 10px',borderRadius:7,cursor:'pointer',marginBottom:5,border:form.jargon_level===o.v?'2px solid #0a66c2':'1.5px solid #dde3ea',background:form.jargon_level===o.v?'#e8f0fb':'#fff',alignItems:'center'}}><span style={{fontWeight:600,fontSize:12,color:form.jargon_level===o.v?'#0a66c2':'#333'}}>{o.l}</span></button>)}</div><div><Lb l="Aktiv / Passiv"/>{VOICE.map(o=><button key={o.v} onClick={()=>s('voice_style')(o.v)} style={{display:'flex',width:'100%',padding:'7px 10px',borderRadius:7,cursor:'pointer',marginBottom:5,border:form.voice_style===o.v?'2px solid #0a66c2':'1.5px solid #dde3ea',background:form.voice_style===o.v?'#e8f0fb':'#fff',alignItems:'center'}}><span style={{fontWeight:600,fontSize:12,color:form.voice_style===o.v?'#0a66c2':'#333'}}>{o.l}</span></button>)}</div></div></>}/><Sc t="Sprach-Richtlinien" ch={<><div><Lb l="Wortwahl"/><Tx v={form.word_choice} fn={s('word_choice')} r={2} ph="Bevorzugt: klar. Vermeiden: Buzzwords..."/></div><div><Lb l="Satzstruktur"/><Tx v={form.sentence_style} fn={s('sentence_style')} r={2} ph="Kurze praegnante Saetze..."/></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><div><Lb l="Dos"/><Tx v={form.dos} fn={s('dos')} r={3} ph="- Fragen stellen&#10;- Beispiele"/></div><div><Lb l="Donts"/><Tx v={form.donts} fn={s('donts')} r={3} ph="- Keine Floskeln&#10;- Kein Spam"/></div></div></>}/></>}
  {tab==='aud'&&<><Sc t="Zielgruppe" ch={<div><Lb l="Wer liest deine Kommentare?"/><Tx v={form.target_audience} fn={s('target_audience')} r={4} ph="B2B-Entscheider, DACH-Region..."/></div>}/><Sc t="Beispieltexte fuer KI-Analyse" ch={<><div><Lb l="Eigene Texte" h="LinkedIn-Posts, Artikel — KI analysiert deinen Stil"/><Tx v={form.example_texts} fn={s('example_texts')} r={7} ph="Fuege hier 2-3 Texte ein die deinen Stil zeigen..."/></div><button onClick={genSummary} disabled={ai} style={{padding:'9px 18px',background:'linear-gradient(135deg,#7c3aed,#a855f7)',color:'#fff',border:'none',borderRadius:18,fontSize:13,fontWeight:700,cursor:'pointer',alignSelf:'flex-start'}}>{ai?'Analysiere...':'KI-Summary generieren'}</button></>}/></>}
  {tab==='sum'&&<Sc t="Brand Voice Summary" ch={<><div><Lb l="AI Summary" h="Wird in alle Kommentare eingebaut"/><Tx v={form.ai_summary} fn={s('ai_summary')} r={9} ph="Noch keine Summary. Tabs ausfullen und KI-Summary generieren."/></div><div style={{padding:'9px 12px',background:'#f0f7ff',borderRadius:7,fontSize:12,color:'#0a66c2'}}>Tipp: Je praeziser die Summary, desto authentischer die Kommentare.</div><button onClick={genSummary} disabled={ai} style={{padding:'8px 16px',background:'linear-gradient(135deg,#7c3aed,#a855f7)',color:'#fff',border:'none',borderRadius:18,fontSize:12,fontWeight:700,cursor:'pointer',alignSelf:'flex-start'}}>{ai?'Generiere...':'Neu generieren'}</button></>}/>}
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'14px 0',borderTop:'1px solid #f0f0f0',marginTop:8}}><button onClick={()=>setEd(null)} style={{padding:'8px 18px',borderRadius:18,background:'#f0f0f0',border:'none',fontSize:13,cursor:'pointer'}}>Abbrechen</button><div style={{display:'flex',gap:10,alignItems:'center'}}>{saved&&<span style={{color:'#057642',fontSize:13,fontWeight:600}}>Gespeichert!</span>}<button onClick={save} disabled={saving||!form.name?.trim()} style={{padding:'8px 22px',borderRadius:18,background:'linear-gradient(135deg,#0a66c2,#0077b5)',color:'#fff',border:'none',fontSize:13,fontWeight:700,cursor:'pointer'}}>{saving?'...':'Brand Voice speichern'}</button></div></div>
</div>)

return(<div style={{maxWidth:800}}>
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:22}}><div><h1 style={{fontSize:21,fontWeight:800,marginBottom:3}}>Brand Voice</h1><p style={{color:'#888',fontSize:13,margin:0}}>Dein Kommunikationsstil wird automatisch in alle Kommentare eingebaut</p></div><button onClick={()=>{setForm({...E0});setEd('new');setTab('id')}} className="btn btn-primary">+ Neue Brand Voice</button></div>
  {voices.length===0?(<div style={{textAlign:'center',padding:'56px 20px',background:'#fff',borderRadius:14,border:'2px dashed #dde3ea'}}><div style={{fontSize:44,marginBottom:14}}>&#127897;</div><div style={{fontSize:17,fontWeight:700,marginBottom:7}}>Noch keine Brand Voice definiert</div><p style={{color:'#888',fontSize:13,marginBottom:20}}>Erstelle deine Brand Voice damit alle Kommentare zu deinem Stil passen.</p><button onClick={()=>{setForm({...E0});setEd('new');setTab('id')}} className="btn btn-primary">Brand Voice erstellen</button></div>):(<div style={{display:'flex',flexDirection:'column',gap:11}}>{voices.map(v=>(<div key={v.id} style={{background:'#fff',borderRadius:11,border:v.is_active?'2px solid #0a66c2':'1.5px solid #eee',padding:'16px 18px'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start'}}><div style={{flex:1}}><div style={{display:'flex',alignItems:'center',gap:9,marginBottom:5}}><span style={{fontWeight:700,fontSize:14}}>{v.name||'Unbenannte Brand Voice'}</span>{v.is_active&&<span style={{padding:'2px 9px',borderRadius:9,fontSize:10,fontWeight:700,background:'#e8f0fb',color:'#0a66c2'}}>Aktiv</span>}</div>{v.brand_name&&<div style={{fontSize:11,color:'#666',marginBottom:3}}>{v.brand_name}</div>}{v.tone_attributes?.length>0&&<div style={{display:'flex',flexWrap:'wrap',gap:4,marginBottom:7}}>{v.tone_attributes.slice(0,5).map(t=><span key={t} style={{padding:'2px 7px',borderRadius:7,fontSize:10,background:'#f0f0f0',color:'#555'}}>{t}</span>)}</div>}{v.ai_summary?<div style={{fontSize:11,color:'#888',background:'#fafafa',borderRadius:7,padding:'7px 9px',lineHeight:1.5}}>{v.ai_summary.slice(0,160)}{v.ai_summary.length>160?'..':''}</div>:<div style={{fontSize:11,color:'#f59e0b'}}>Noch keine KI-Summary</div>}</div><div style={{display:'flex',gap:7,marginLeft:14,flexShrink:0}}>{!v.is_active&&<button onClick={()=>activate(v.id)} className="btn btn-sm btn-secondary" style={{fontSize:10}}>Aktivieren</button>}<button onClick={()=>{setForm({...v});setEd(v);setTab('id')}} className="btn btn-sm btn-secondary" style={{fontSize:10}}>Bearbeiten</button><button onClick={async()=>{if(confirm('Loeschen?')){await supabase.from('brand_voices').delete().eq('id',v.id);load()}}} className="btn btn-sm btn-danger" style={{fontSize:10}}>X</button></div></div></div>))}</div>)}
</div>)
}
